# Generated by Django 4.0.3 on 2023-07-29 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_emg_value_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emg_value',
            name='author',
        ),
        migrations.DeleteModel(
            name='EMG_user_data',
        ),
        migrations.DeleteModel(
            name='EMG_value',
        ),
    ]
