# Generated by Django 4.0.3 on 2023-07-29 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_value_emg_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='author_data',
            field=models.ForeignKey(db_column='author_data', on_delete=django.db.models.deletion.CASCADE, to='main.emg_data'),
        ),
    ]
