# Generated by Django 4.0.3 on 2023-07-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_value_author_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='author_data',
        ),
        migrations.DeleteModel(
            name='EMG_data',
        ),
        migrations.DeleteModel(
            name='value',
        ),
    ]
