# Generated by Django 4.0.3 on 2023-07-24 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Startpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
